version: '3.8'

services:
  exchange-rate-api:
    build: .
    container_name: exchange-rate-api
    ports:
      - "5055:5055"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # ✅ Cambiar a Development para habilitar Swagger
      - ASPNETCORE_URLS=http://+:5055
      # URLs de APIs internas (dentro del contenedor)
      - ExchangeRateApis__Api1__Url=http://localhost:5055/api1
      - ExchangeRateApis__Api2__Url=http://localhost:5055/api2
      - ExchangeRateApis__Api3__Url=http://localhost:5055/api3
      - ExchangeRateApis__Api1__TimeoutSeconds=10
      - ExchangeRateApis__Api2__TimeoutSeconds=15
      - ExchangeRateApis__Api3__TimeoutSeconds=12
      - ExchangeRateApis__Api1__AuthType=ApiKey
      - ExchangeRateApis__Api2__AuthType=ApiKey
      - ExchangeRateApis__Api3__AuthType=ApiKey
      - ExchangeRateApis__Api1__IsEnabled=true
      - ExchangeRateApis__Api2__IsEnabled=true
      - ExchangeRateApis__Api3__IsEnabled=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
networks:
  default:
    name: exchange-rate-network